// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ratzrtjzexsyikhucroq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdHpydGp6ZXhzeWlraHVjcm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzIzNDMsImV4cCI6MjA3MjIwODM0M30.qQaYki82iEzIjXCv-JXh-N_MDMC8ZSUP7LJwYs0g6aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});